# Generated by Django 2.1.5 on 2019-10-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Not willing to share', 'Not willing to share'), ('Male', 'Male'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default='Not willing to share', max_length=20)),
                ('phone', models.IntegerField(db_index=True, max_length=15, primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
