# Generated by Django 2.1.5 on 2019-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('NOT WILLING TO SHARE', 'NOT WILLING TO SHARE'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default='NOT WILLING TO SHARE', max_length=20)),
                ('phone', models.CharField(db_index=True, max_length=16)),
                ('address', models.TextField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nadi', models.CharField(max_length=30)),
                ('jihwa', models.CharField(max_length=30)),
                ('mutra', models.CharField(max_length=30)),
                ('drit', models.CharField(max_length=30)),
                ('malam', models.CharField(max_length=30)),
                ('sabdam', models.CharField(max_length=30)),
                ('atriti', models.CharField(max_length=30)),
                ('sparsha', models.CharField(max_length=30)),
                ('dushyam', models.CharField(max_length=30)),
                ('prakriti', models.CharField(max_length=30)),
                ('desha', models.CharField(max_length=30)),
                ('vaya', models.CharField(max_length=30)),
                ('bala', models.CharField(max_length=30)),
                ('satwa', models.CharField(max_length=30)),
                ('kala', models.CharField(max_length=30)),
                ('sathmaya', models.CharField(max_length=30)),
                ('anala', models.CharField(max_length=30)),
                ('ahara', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=30, null=True)),
                ('weight', models.CharField(max_length=30, null=True)),
                ('pulse', models.CharField(max_length=30, null=True)),
                ('blood_pressure', models.CharField(max_length=30, null=True)),
                ('heart_rate', models.CharField(max_length=30, null=True)),
                ('other_examination', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
