# Generated by Django 2.1.5 on 2019-10-12 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesheet',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casesheet',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='casesheet', to='core.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casesheet',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casesheet',
            name='treatments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casesheet',
            name='visit_data',
            field=models.DateField(auto_now=True),
        ),
    ]
