# Generated by Django 2.1.5 on 2019-10-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmanagement',
            name='medicine_category',
            field=models.CharField(choices=[('Arishtas/ asavas', 'Arishtas/ asavas'), ('Kashaya churnam', 'Kashaya churnam'), ('Kashaya sukshma churnam', 'Kashaya sukshma churnam'), ('kashaya', 'kashaya'), ('Kashaya tablet', 'Kashaya tablet'), ('Churnam', 'Churnam'), ('Gutika', 'Gutika'), ('Ghritha', 'Ghritha'), ('Lehyam', 'Lehyam'), ('syrups', 'syrups'), ('drops', 'drops'), ('lepam', 'lepam'), ('Bhasmas', 'Bhasmas'), ('Taila', 'Taila'), ('Patent tablets/capsules', 'Patent tablets/capsules'), ('Cosmetic', 'Cosmetic'), ('Nutraceuticals', 'Nutraceuticals')], max_length=150),
        ),
        migrations.DeleteModel(
            name='StockCategory',
        ),
    ]
