# Generated by Django 2.1.5 on 2019-10-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
