# Generated by Django 2.1.5 on 2019-10-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
