# Generated by Django 2.1.5 on 2019-10-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='heart_rat',
            new_name='heart_rate',
        ),
    ]
