# Generated by Django 2.1.5 on 2019-10-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191019_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_category', models.CharField(choices=[('cat1', 'cat1'), ('cat2', 'cat2'), ('cat3', 'cat3')], default='cat1', max_length=50)),
                ('medicine_name', models.CharField(db_index=True, max_length=150)),
                ('universal_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('quantity', models.IntegerField()),
                ('manufacturer', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
