# Generated by Django 2.1.5 on 2019-10-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191012_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casesheet',
            old_name='prescription',
            new_name='complaints',
        ),
        migrations.RenameField(
            model_name='casesheet',
            old_name='visit_data',
            new_name='visit_date',
        ),
        migrations.AddField(
            model_name='casesheet',
            name='prescriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
