# Generated by Django 2.1.5 on 2019-10-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191007_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='other_examination',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
