# Generated by Django 2.1.5 on 2019-10-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191012_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='atriti',
            new_name='akriti',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='drit',
            new_name='drik',
        ),
    ]
