# Generated by Django 2.1.5 on 2019-10-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191007_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='other_examination',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
