# Generated by Django 2.1.5 on 2019-10-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191013_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='sathmaya',
            new_name='sathmya',
        ),
    ]
