# Generated by Django 2.1.5 on 2019-10-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191007_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='other_examination',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
