# Generated by Django 2.1.5 on 2019-10-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191008_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False),
        ),
    ]
